// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvEBQ4prPlXCiG5Q_TscaBAhixagT8kEA',
    appId: '1:141081771541:web:1982a4ac8795f91669d81c',
    messagingSenderId: '141081771541',
    projectId: 'chat-app-8c96b',
    authDomain: 'chat-app-8c96b.firebaseapp.com',
    storageBucket: 'chat-app-8c96b.appspot.com',
    measurementId: 'G-6LJMV2G5YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5AdwSs2Z05VDpBSXrLK_rCgv88JUjpVg',
    appId: '1:141081771541:android:a2d1b2a89d628ac369d81c',
    messagingSenderId: '141081771541',
    projectId: 'chat-app-8c96b',
    storageBucket: 'chat-app-8c96b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3iVGJOJx5oS-5pyxhfLuSGDu2xClmgGw',
    appId: '1:141081771541:ios:dfe83703b557038569d81c',
    messagingSenderId: '141081771541',
    projectId: 'chat-app-8c96b',
    storageBucket: 'chat-app-8c96b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3iVGJOJx5oS-5pyxhfLuSGDu2xClmgGw',
    appId: '1:141081771541:ios:f67a213a0116275869d81c',
    messagingSenderId: '141081771541',
    projectId: 'chat-app-8c96b',
    storageBucket: 'chat-app-8c96b.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
